version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: CustomerService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  customer-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: Host=db;Port=5432;Database=CustomerService;Username=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "8080:80"
  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: dotnet test /src/customer-api.tests/customer-api.tests.csproj
    depends_on:
      - db

volumes:
  pgdata: